# Make sure that you have the database uploaded and you have installed libmysql-java.
# Your class path might be different.
compile:
	javac MysqlCon.java

run: compile
	java -cp /usr/share/java/mysql-connector-java-5.1.28.jar:. MysqlCon

clean:
	rm -rf *class
